### ISSUE TITLE
expose vpn name setting in vpn settings

### ISSUE THREAD

**Issue by Fuseteam** [ubports/indicator-network#16]
after setting up a vpn the servers ip address is shown in the network indicator
name should be exposed in vpn settings so that a common name can shown in the network indicator instead

**Comment by Fuseteam** [comment]
the [source](https://github.com/unity8-team/indicator-network/tree/master/src/vpn-editor) of the [VPN Editor](https://open-store.io/app/com.ubuntu.developer.pete-woods.vpn-editor) in the open store looks like a fork/clone of this [repo](https://github.com/ubports/indicator-network/tree/xenial/src/vpn-editor) or perhaps the otherway around hmmmm could we merge that in here to expose the vpn name aswell as other options?

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-indicator-network/-/issues/16

Sorry for your inconvenience.
