### ISSUE TITLE
Access to "mobile data configuration" and "wireless network configuration" above the network names

### ISSUE THREAD

**Issue by ghost** [ubports/indicator-network#25]
See this [forum post](https://forums.ubports.com/topic/3021/access-to-mobile-data-configuration-and-wireless-network-configuration-above-the-network-names).

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-indicator-network/-/issues/25

Sorry for your inconvenience.
