### ISSUE TITLE
Dropdown network speed indicator does not reflect current state, but configured one

### ISSUE THREAD

**Issue by Flohack74** [ubports/indicator-network#29]
When the network indicator is pulled down, it shows the carrier network info (name, technology). It is a bit confusing that the technology icon there shows the connection speed that would be _possible_ with the settings for this SIM card, while the indicator on the top shows the _actual_ speed.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-indicator-network/-/issues/29

Sorry for your inconvenience.
