### ISSUE TITLE
Change WiFi to WLAN do it to  Wi-Fi Alliance. All rights reserved. Wi-Fi® 

### ISSUE THREAD

**Issue by carlosgonz0** [ubports/indicator-network#31]
May be  better the sentence 'WLAN' than 'WI-FI" on a Truly GNU-Linux Mobile.
 https://www.wi-fi.org

**Comment by mateosalta** [comment]
bluetooth is also (r)

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-indicator-network/-/issues/31

Sorry for your inconvenience.
