### ISSUE TITLE
VPN - show more info

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/indicator-network#4]
When a vpn is connected, underneath the vpn which is connected, you should be able to see more information, such as ip address and connection speeds.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-indicator-network/-/issues/4

Sorry for your inconvenience.
