### ISSUE TITLE
Wifi - Show if connected to the internet or not

### ISSUE THREAD

**Issue by cyberpunkedu** [ubports/indicator-network#5]
Currently the wifi indicator shows if you are connected or not to a wifi signal, but there is no indication if there is any data transfer or Internet connectivity.

On some other OS there is a "!" symbol to indicate that there is no internet connection though you are connected to the wifi signal.

Maybe the same as this ubports/ubuntu-touch#68

**Comment by userj** [comment]
Maybe the same as this https://github.com/ubports/ubuntu-touch/issues/68

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-indicator-network/-/issues/5

Sorry for your inconvenience.
