### ISSUE TITLE
Indicator does not show network provider

### ISSUE THREAD

**Issue by OhneZ007** [ubports/indicator-network#55]
Hello, a help would be if the indicator would show also the name of the network provider. for example on the left side.
This would help when roaming to quickly see if the correct network provider was selected.
Greetings
Steffen

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-indicator-network/-/issues/55

Sorry for your inconvenience.
