### ISSUE TITLE
Cellular data connection not established after reboot

### ISSUE THREAD

**Issue by mardy** [ubports/indicator-network#70]
Image: OTA18 (happens on devel too)
Device: `lavender` and `violet`

#### Steps to reproduce:
1. Insert two SIMS. The one in the second slot must have a valid 4G contract for data transfer.
2. In system settings, set the first SIM to 2G connection
3. In system settings, set the second SIM to 4G connection
4. In system settings, choose the second SIM as the one to be used for cellular data transfer
5. Enable the data connection (the connection will be established, and will be 4G)
6. Reboot
7. Without opening the system settings, enable the data connection from the indicator

#### Expected outcome
A 4G data connection is established on the second SIM.

#### Actual outcome
A "2G" symbol appears next to the second SIM. The network connection is never established.

I'm experiencing this bug both with `violet` and `lavender`, so it might be affecting all halium9 devices.

**Comment by mardy** [comment]
This is fixed by https://github.com/ubports/indicator-network/pull/59

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-indicator-network/-/issues/70

Sorry for your inconvenience.
