### ISSUE TITLE
instable network connection, problems when changing network mobile <> wifi

### ISSUE THREAD

**Issue by Danfro** [ubports/indicator-network#72]
With Xperia X I recently have quite often that nework (wifi) does not stay connected. Also when changing from wifi to mobile a connection is not established or wifi does not get reconnected when coming back.

This sadly is nothing I could pinpoint to a certain behaviour but seems to happen randomly. Sometimes it works, sometimes it doesn't.

I can't provide more data or description but still wanted to raise the issue so others can comment in case they experience the same.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-indicator-network/-/issues/72

Sorry for your inconvenience.
