### ISSUE TITLE
In-tree builds are unsupported, but not prohibited by cmake

### ISSUE THREAD

**Issue by vanyasem** [ubports/indicator-network#8]

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-indicator-network/-/issues/8

Sorry for your inconvenience.
